name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Check Go version
        run: go version  # This will verify Go installation

      - name: Install dependencies
        run: |
          go mod tidy
          go mod verify  # Ensures dependencies are correctly installed

      - name: Build the application
        run: |
          go build -o main .
          if [ ! -f main ]; then
            echo "Build failed, 'main' executable not found!"
            exit 1
          fi

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/golangprojects:latest .
          docker push ${{ secrets.DOCKERUSERNAME }}/golangprojects:latest

      - name: Verify Docker image exists
        run: |
          docker pull ${{ secrets.DOCKERUSERNAME }}/golangprojects:latest
