name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this pipeline on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the application
      - name: Build
        run: go build -o main .

      # Run tests (if test cases are added later)
      # - name: Run tests
      #   run: go test ./...

      # Build a Docker image
      - name: Build Docker Image
        run: |
          docker build -t golangprojects:latest .

      # Push Docker image to DockerHub (optional, configure this later)
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Docker Image
      #   run: |
      #     docker tag golangprojects:latest username/golangprojects:latest
      #     docker push username/golangprojects:latest
